name: "Package and Release Scripts"
run-name: "Release package triggered by @${{ github.actor }}"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'

jobs:
  package-release:
    name: "Package and Release Scripts"
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - run: git archive -9 -o latest.tar.gz HEAD
        name: Archive Repository
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: latest.tar.gz
          generate_release_notes: true
          make_latest: "true"
